# Generated by Django 5.0.6 on 2024-06-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="receipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipe_name", models.CharField(max_length=500)),
                ("receipe_description", models.TextField()),
                ("receipe_image", models.ImageField(upload_to="receipe")),
            ],
        ),
    ]
